"""
loaders.py — Pull data from existing Marketing Agents outputs.
No new APIs. Reads files already generated by other agents.
"""
import json, sqlite3
from pathlib import Path
from datetime import datetime, timedelta


def load_all(project_root: Path, since_days: int = 7) -> dict:
    since = (datetime.now() - timedelta(days=since_days)).strftime("%Y-%m-%d")
    return {
        "trends":  _load_trends(project_root),
        "reddit":  _load_reddit(project_root),
        "rss":     _load_rss(project_root, since),
        "tavily":  _load_tavily(project_root, since),
    }


def _load_trends(root: Path) -> list[dict]:
    """All TIMESERIES JSON files from Serpi_feeder → flat keyword list."""
    out = []
    data_dir = root / "Serpi_feeder" / "data"
    if not data_dir.exists():
        return out
    for f in data_dir.rglob("*TIMESERIES*.json"):
        try:
            raw = json.loads(f.read_text(encoding="utf-8"))
            meta = raw.get("_meta", {})
            timeline = raw.get("interest_over_time", {}).get("timeline_data", [])
            for idx, kw in enumerate(meta.get("keywords", [])):
                series = []
                for pt in timeline:
                    vals = pt.get("values", [])
                    v = vals[idx] if idx < len(vals) else {}
                    series.append({
                        "date": pt.get("date", ""),
                        "value": v.get("extracted_value", 0),
                        "is_partial": pt.get("partial_data", False),
                    })
                avg = sum(p["value"] for p in series if not p["is_partial"])
                avg = round(avg / max(len([p for p in series if not p["is_partial"]]), 1), 1)
                out.append({"keyword": kw.lower(), "avg": avg, "market": meta.get("market", "")})
        except Exception as e:
            print(f"  ⚠ trends load error {f.name}: {e}")
    return out


def _load_reddit(root: Path) -> list[dict]:
    p = root / "reddit_watcher" / "output" / "reddit_raw.json"
    if not p.exists() or p.stat().st_size == 0:
        return []
    try:
        posts = json.loads(p.read_text(encoding="utf-8"))
        for post in posts:
            post["source_type"] = "reddit"
        return posts
    except Exception as e:
        print(f"  ⚠ reddit load error: {e}")
        return []


def _load_rss(root: Path, since: str) -> list[dict]:
    db = root / "RSS_Feeder" / "db" / "news.db"
    if not db.exists():
        return []
    conn = sqlite3.connect(str(db))
    c = conn.cursor()
    c.execute("""
        SELECT title, summary, link, score, matched_keywords, fetched_date
        FROM news WHERE fetched_date >= ?
        ORDER BY score DESC
    """, (since,))
    rows = c.fetchall()
    conn.close()
    out = []
    for row in rows:
        try:
            kws = json.loads(row[4] or "[]")
        except Exception:
            kws = []
        out.append({
            "title": row[0] or "", "summary": row[1] or "",
            "link": row[2] or "", "score": row[3] or 0,
            "matched_keywords": kws, "fetched_date": row[5] or "",
            "source_type": "rss",
        })
    return out


def _load_tavily(root: Path, since: str) -> list[dict]:
    results_dir = root / "tavily_feeder" / "results"
    if not results_dir.exists():
        return []
    since_dt = datetime.strptime(since, "%Y-%m-%d")
    out = []
    for f in sorted(results_dir.glob("*.json")):
        try:
            if datetime.strptime(f.stem[:10], "%Y-%m-%d") < since_dt:
                continue
            raw = json.loads(f.read_text(encoding="utf-8"))
            for entry in raw.get("search_results", []):
                for r in entry.get("results", []):
                    out.append({
                        "title": r.get("title", ""),
                        "content": r.get("content", ""),
                        "url": r.get("url", ""),
                        "score": r.get("score", 0),
                        "subject": entry.get("subject", ""),
                        "source_type": "tavily",
                    })
        except Exception:
            pass
    return out